return {
	['none'] = false,
	['titleLogo'] = true,
	['titleColours'] = true,
	['matureReferences_cyc'] = 1,
	['playingCardTextures'] = true,
	['malverkReplacements'] = true,
	['jokerRenames'] = true,
	['allowCosmeticTakeOwnership'] = true,
	['addCustomJokers'] = true,
	['addCustomConsumables'] = true,
	['negativePCardsBalancing'] = true,
	['blindRenames'] = true,
	['deckRenames'] = true,
	['enhancerRenames'] = true,
	['planetsAreHus'] = true,
	['planetTarotSpectralRenames'] = true,
	['miscRenames'] = true,
	['additionalChallenges'] = false,
	['artCredits'] = true,
	['encounteredJokers'] = {{},{},{}}
}