SMODS.process_loc_text(G.localization.descriptions.Blind.bl_arm, "name", "The Wan Wan")
SMODS.process_loc_text(G.localization.descriptions.Blind.bl_club, "name", "The Cirnium")
SMODS.process_loc_text(G.localization.descriptions.Blind.bl_eye, "name", "The 'I See'")
-- SMODS.process_loc_text(G.localization.descriptions.Blind.bl_fish, "name", "")
SMODS.process_loc_text(G.localization.descriptions.Blind.bl_flint, "name", "The Poison Swamp")
SMODS.process_loc_text(G.localization.descriptions.Blind.bl_goad, "name", "The")
SMODS.process_loc_text(G.localization.descriptions.Blind.bl_head, "name", "The... What Do I Do?")
-- SMODS.process_loc_text(G.localization.descriptions.Blind.bl_hook, "name", "")
SMODS.process_loc_text(G.localization.descriptions.Blind.bl_house, "name", "The Whale")
SMODS.process_loc_text(G.localization.descriptions.Blind.bl_manacle, "name", "The Memory")
SMODS.process_loc_text(G.localization.descriptions.Blind.bl_mark, "name", "The No Dabbing")
SMODS.process_loc_text(G.localization.descriptions.Blind.bl_mouth, "name", "The Possessed")
SMODS.process_loc_text(G.localization.descriptions.Blind.bl_needle, "name", "The Peer")
SMODS.process_loc_text(G.localization.descriptions.Blind.bl_ox, "name", "The Hehehe")
SMODS.process_loc_text(G.localization.descriptions.Blind.bl_pillar, "name", "The Poggers")
SMODS.process_loc_text(G.localization.descriptions.Blind.bl_plant, "name", "The Obsession")
SMODS.process_loc_text(G.localization.descriptions.Blind.bl_psychic, "name", "The 9Head")
SMODS.process_loc_text(G.localization.descriptions.Blind.bl_serpent, "name", "The Deal")
-- SMODS.process_loc_text(G.localization.descriptions.Blind.bl_tooth, "name", "")
SMODS.process_loc_text(G.localization.descriptions.Blind.bl_wall, "name", "Old Faithful")
SMODS.process_loc_text(G.localization.descriptions.Blind.bl_wheel, "name", "The O")
-- SMODS.process_loc_text(G.localization.descriptions.Blind.bl_window, "name", "")

SMODS.process_loc_text(G.localization.descriptions.Blind.bl_final_acorn, "name", "Amber Attack")
-- SMODS.process_loc_text(G.localization.descriptions.Blind.bl_final_bell, "name", "")
-- SMODS.process_loc_text(G.localization.descriptions.Blind.bl_final_heart, "name", "")
SMODS.process_loc_text(G.localization.descriptions.Blind.bl_final_leaf, "name", "Verdant Vehemence")
SMODS.process_loc_text(G.localization.descriptions.Blind.bl_final_vessel, "name", "Violet Donowall")